hooks:
  post-start:
    - exec: 'sh -c "[ ! -d data-snapshot20250710 ] && npm run build || exit 0"'
      service: app

      # Detects to see if the node_modules folder exists
    - exec: 'sh -c "[ ! -d node_modules ] && npm ci || exit 0"'
      service: app
