services:
  app:
    container_name: ddev-${DDEV_PROJECT}-app
    build:
      context: ./../app
    restart: unless-stopped
    environment:
      - PORT=3000
      - ES_URL_NO_AUTH=http://opensearch:9200
      - ES_USERNAME=admin
      - ES_PASSWORD=97UxngYAArZ12jqt!jH20K
      - ES_index=objects2
      - REDIS_URL=redis://redis:6379
      - IS_LOCAL=1
    ports:
      - "3000:3000"
    volumes:
      - ./../app:/app
