services:
  opensearch:
    image: opensearchproject/opensearch:2.19.2
    container_name: ddev-${DDEV_PROJECT}-opensearch
    environment:
      - discovery.type=single-node
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=eUyt#&n&7cJ!
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
