services:
  redis:
    image: redis:7-alpine
    container_name: ddev-${DDEV_PROJECT}-redis
    restart: unless-stopped
    ports:
      - "6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
